
class Defines():
    PLAYERTYPE_QB = "QB "
    PLAYERTYPE_RB = "RB "
    PLAYERTYPE_WR = "WR "
    PLAYERTYPE_TE = "TE "
    PLAYERTYPE_DST = "DST"
    PLAYERTYPE_KICKER = "K  "

    PLAYERSTATUS_QB     = 0
    PLAYERSTATUS_RB1    = 1
    PLAYERSTATUS_RB2    = 2
    PLAYERSTATUS_WR1    = 3
    PLAYERSTATUS_WR2    = 4
    PLAYERSTATUS_TE     = 5
    PLAYERSTATUS_FLEX   = 6
    PLAYERSTATUS_DST    = 7
    PLAYERSTATUS_KICKER = 8
    PLAYERSTATUS_BENCH  = 9

if __name__ == '__main__':
    main()
